### ISSUE TITLE
MainPageNameData.java not completely updated

### ISSUE THREAD

**Issue by noni-mizu** [akvo/Akvopedia_App#3]
When we changed the main page name, we changed the first `.put` from `Main Page` to `Akvopedia mobile`. But we did not change the very last line in that method also to `Akvopedia mobile` for testing. It would take a simple edit to this file:

```
private static void setupData() {
...
DATA_MAP.put("test", "Akvopedia mobile"); // change home page of app here for testing
}
```

**Comment by nhternup** [comment]
Change made in https://github.com/akvo/Akvopedia_App/commit/9a9c6f5e5d77936ae7a5cc14c632f637f1f8d7b6
